<main class="container">
    <div class="row">
        <div class="col-12 mt-5">
          <h1 class="text-center">HOME</h1>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum voluptatibus nostrum atque quas ad. Ex molestias suscipit illum possimus officiis harum, sequi dicta aut similique accusamus sapiente delectus animi laboriosam placeat consectetur nisi praesentium non nostrum exercitationem quod. Quas facilis ipsum ipsa quod quaerat sed doloremque mollitia porro. Soluta velit pariatur at dolorem impedit maxime, fuga architecto voluptas, dignissimos fugiat adipisci. Fuga accusantium accusamus quia, voluptatum magnam fugiat voluptatibus soluta doloribus distinctio. Dolore quisquam velit repellendus voluptatum nemo dolores consequuntur, eius incidunt sapiente omnis tenetur facilis eum modi enim consequatur dignissimos natus nobis doloribus fugit cumque ullam illo doloremque hic molestiae? Possimus quibusdam quidem quae dignissimos, quod voluptate, iusto ea corrupti porro, non vitae illo? Minus voluptatibus dolore assumenda? Error quaerat ex iure rem quis quo adipisci asperiores fuga, aspernatur, exercitationem ea a dolore quasi consectetur qui id quia impedit, perferendis quas amet culpa. Maxime praesentium iure aut odit laborum veritatis ex, vero ducimus asperiores officiis atque cum culpa aperiam animi quas. Itaque numquam accusamus repudiandae officiis harum aspernatur atque eius facere corrupti vitae provident rerum ea impedit explicabo cumque corporis sequi earum, qui iusto natus. Est illo perspiciatis corporis neque dolore vero, distinctio, laborum veritatis laboriosam, consectetur quisquam qui!</p>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum voluptatibus nostrum atque quas ad. Ex molestias suscipit illum possimus officiis harum, sequi dicta aut similique accusamus sapiente delectus animi laboriosam placeat consectetur nisi praesentium non nostrum exercitationem quod. Quas facilis ipsum ipsa quod quaerat sed doloremque mollitia porro. Soluta velit pariatur at dolorem impedit maxime, fuga architecto voluptas, dignissimos fugiat adipisci. Fuga accusantium accusamus quia, voluptatum magnam fugiat voluptatibus soluta doloribus distinctio. Dolore quisquam velit repellendus voluptatum nemo dolores consequuntur, eius incidunt sapiente omnis tenetur facilis eum modi enim consequatur dignissimos natus nobis doloribus fugit cumque ullam illo doloremque hic molestiae? Possimus quibusdam quidem quae dignissimos, quod voluptate, iusto ea corrupti porro, non vitae illo? Minus voluptatibus dolore assumenda? Error quaerat ex iure rem quis quo adipisci asperiores fuga, aspernatur, exercitationem ea a dolore quasi consectetur qui id quia impedit, perferendis quas amet culpa. Maxime praesentium iure aut odit laborum veritatis ex, vero ducimus asperiores officiis atque cum culpa aperiam animi quas. Itaque numquam accusamus repudiandae officiis harum aspernatur atque eius facere corrupti vitae provident rerum ea impedit explicabo cumque corporis sequi earum, qui iusto natus. Est illo perspiciatis corporis neque dolore vero, distinctio, laborum veritatis laboriosam, consectetur quisquam qui!</p>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum voluptatibus nostrum atque quas ad. Ex molestias suscipit illum possimus officiis harum, sequi dicta aut similique accusamus sapiente delectus animi laboriosam placeat consectetur nisi praesentium non nostrum exercitationem quod. Quas facilis ipsum ipsa quod quaerat sed doloremque mollitia porro. Soluta velit pariatur at dolorem impedit maxime, fuga architecto voluptas, dignissimos fugiat adipisci. Fuga accusantium accusamus quia, voluptatum magnam fugiat voluptatibus soluta doloribus distinctio. Dolore quisquam velit repellendus voluptatum nemo dolores consequuntur, eius incidunt sapiente omnis tenetur facilis eum modi enim consequatur dignissimos natus nobis doloribus fugit cumque ullam illo doloremque hic molestiae? Possimus quibusdam quidem quae dignissimos, quod voluptate, iusto ea corrupti porro, non vitae illo? Minus voluptatibus dolore assumenda? Error quaerat ex iure rem quis quo adipisci asperiores fuga, aspernatur, exercitationem ea a dolore quasi consectetur qui id quia impedit, perferendis quas amet culpa. Maxime praesentium iure aut odit laborum veritatis ex, vero ducimus asperiores officiis atque cum culpa aperiam animi quas. Itaque numquam accusamus repudiandae officiis harum aspernatur atque eius facere corrupti vitae provident rerum ea impedit explicabo cumque corporis sequi earum, qui iusto natus. Est illo perspiciatis corporis neque dolore vero, distinctio, laborum veritatis laboriosam, consectetur quisquam qui!</p>
        </div>
    </div>
</main>
