<?php

require_once "classes/Viagem.php";
require_once "classes/Banner.php";

$viagens = [
  new Viagem("Lisboa", "public/imagens/lisboa.jpg", "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Iure, molestias doloribus. Commodi sit nisi vel fuga facilis, quidem ipsam recusandae laudantium obcaecati. Quidem voluptatem laboriosam alias sed ullam nostrum voluptate et nobis, ad atque dolor eveniet laborum officiis veritatis, aspernatur dolorum architecto sapiente modi enim. Eius labore cumque nemo explicabo aliquam? Distinctio blanditiis eaque excepturi beatae ex eligendi ad est, doloribus consequuntur accusamus autem omnis aut earum sed! Accusamus optio veritatis dolor. Eligendi molestias corporis dicta vel praesentium voluptatibus commodi est tempora repellendus, minima earum maiores reiciendis quis quos ea dolorem numquam porro iste aspernatur! Nisi neque odit animi repudiandae laboriosam quos error! Iste fugit, quos expedita eaque eos illo quisquam? Doloribus distinctio soluta repellat obcaecati incidunt quod odio expedita ea voluptates, quisquam dolorum ab voluptas nemo voluptatum. Ab obcaecati nulla ullam odio suscipit harum aut eveniet architecto maiores repellat, rerum recusandae officiis optio eaque vel, inventore voluptatum dicta numquam quia illo quae! Sit, expedita pariatur. Totam consequuntur eligendi dolor similique veniam maxime error sequi temporibus molestiae amet aspernatur, ducimus dolorum eum ipsum perspiciatis minima ipsa voluptatum dolore hic odio qui ab! Cupiditate nesciunt similique voluptatum veniam cum inventore, voluptates amet iste laboriosam blanditiis maxime facere nam delectus. Debitis, velit."),
  new Viagem("Porto", "public/imagens/porto_01.jpg", "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Iure, molestias doloribus. Commodi sit nisi vel fuga facilis, quidem ipsam recusandae laudantium obcaecati. Quidem voluptatem laboriosam alias sed ullam nostrum voluptate et nobis, ad atque dolor eveniet laborum officiis veritatis, aspernatur dolorum architecto sapiente modi enim. Eius labore cumque nemo explicabo aliquam? Distinctio blanditiis eaque excepturi beatae ex eligendi ad est, doloribus consequuntur accusamus autem omnis aut earum sed! Accusamus optio veritatis dolor. Eligendi molestias corporis dicta vel praesentium voluptatibus commodi est tempora repellendus, minima earum maiores reiciendis quis quos ea dolorem numquam porro iste aspernatur! Nisi neque odit animi repudiandae laboriosam quos error! Iste fugit, quos expedita eaque eos illo quisquam? Doloribus distinctio soluta repellat obcaecati incidunt quod odio expedita ea voluptates, quisquam dolorum ab voluptas nemo voluptatum. Ab obcaecati nulla ullam odio suscipit harum aut eveniet architecto maiores repellat, rerum recusandae officiis optio eaque vel, inventore voluptatum dicta numquam quia illo quae! Sit, expedita pariatur. Totam consequuntur eligendi dolor similique veniam maxime error sequi temporibus molestiae amet aspernatur, ducimus dolorum eum ipsum perspiciatis minima ipsa voluptatum dolore hic odio qui ab! Cupiditate nesciunt similique voluptatum veniam cum inventore, voluptates amet iste laboriosam blanditiis maxime facere nam delectus. Debitis, velit."),
  new Viagem("Serra da Estrela", "public/imagens/serra.jpg", "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Iure, molestias doloribus. Commodi sit nisi vel fuga facilis, quidem ipsam recusandae laudantium obcaecati. Quidem voluptatem laboriosam alias sed ullam nostrum voluptate et nobis, ad atque dolor eveniet laborum officiis veritatis, aspernatur dolorum architecto sapiente modi enim. Eius labore cumque nemo explicabo aliquam? Distinctio blanditiis eaque excepturi beatae ex eligendi ad est, doloribus consequuntur accusamus autem omnis aut earum sed! Accusamus optio veritatis dolor. Eligendi molestias corporis dicta vel praesentium voluptatibus commodi est tempora repellendus, minima earum maiores reiciendis quis quos ea dolorem numquam porro iste aspernatur! Nisi neque odit animi repudiandae laboriosam quos error! Iste fugit, quos expedita eaque eos illo quisquam? Doloribus distinctio soluta repellat obcaecati incidunt quod odio expedita ea voluptates, quisquam dolorum ab voluptas nemo voluptatum. Ab obcaecati nulla ullam odio suscipit harum aut eveniet architecto maiores repellat, rerum recusandae officiis optio eaque vel, inventore voluptatum dicta numquam quia illo quae! Sit, expedita pariatur. Totam consequuntur eligendi dolor similique veniam maxime error sequi temporibus molestiae amet aspernatur, ducimus dolorum eum ipsum perspiciatis minima ipsa voluptatum dolore hic odio qui ab! Cupiditate nesciunt similique voluptatum veniam cum inventore, voluptates amet iste laboriosam blanditiis maxime facere nam delectus. Debitis, velit."),
];

$carousel = [
  new Banner("Título 1", "public/imagens/paisagem_1.avif", "Sou o texto 1"),
  new Banner("Título 2", "public/imagens/paisagem_2.avif", "Sou o texto 2"),
  new Banner("Título 3", "public/imagens/paisagem_3.avif", "Sou o texto 3"),
  new Banner("Título 4", "public/imagens/paisagem_4.avif", "Sou o texto 4"),
  new Banner("Título 5", "public/imagens/paisagem_5.avif", "Sou o texto 5"),
];




?>